//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct AccessTokenResponse: Content {

    public var accessToken: String

    public var tokenType: String

    /** Note that the expires_in field represents a value in seconds. This conforms to the OAuth spec for token responses. More information regarding this can be found in the OAuth 2.0 Authorization Framework spec (https://tools.ietf.org/html/rfc6749#section-4.2.2) */
    public var expiresIn: Int

    public var refreshToken: String

    public var scope: String

    enum CodingKeys: String, CodingKey {
        case accessToken = "access_token"
        case tokenType = "token_type"
        case expiresIn = "expires_in"
        case refreshToken = "refresh_token"
        case scope = "scope"
    }

}
