//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct Runtime: Content {

    public var runtimeRev: String

    public var connected: Bool

    public var firstConnected: Int

    enum CodingKeys: String, CodingKey {
        case runtimeRev = "runtimeRev"
        case connected = "connected"
        case firstConnected = "firstConnected"
    }

}
