//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct ThermostatPage: Content {

    public var page: Int

    public var totalPages: Int

    public var pageSize: Int

    public var total: Int

    enum CodingKeys: String, CodingKey {
        case page = "page"
        case totalPages = "totalPages"
        case pageSize = "pageSize"
        case total = "total"
    }

}
