//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct Thermostat: Content {

    public var identifier: String

    public var name: String

    public var thermostateRev: String

    public var isRegistered: Bool

    public var modelNumber: String

    public var brand: String

    public var features: String

    public var runtime: Runtime

    enum CodingKeys: String, CodingKey {
        case identifier = "identifier"
        case name = "name"
        case thermostateRev = "thermostateRev"
        case isRegistered = "isRegistered"
        case modelNumber = "modelNumber"
        case brand = "brand"
        case features = "features"
        case runtime = "runtime"
    }

}
