//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct ThermostatResponse: Content {

    public var page: ThermostatPage

    public var thermostatList: [Thermostat]

    enum CodingKeys: String, CodingKey {
        case page = "page"
        case thermostatList = "thermostatList"
    }

}
