//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

extension Client {
   func getThermostatSummary(headers:  HTTPHeaders) -> EventLoopFuture<AccessTokenResponse> {
      send(.GET, headers: headers, to: "/thermostatSummary")
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(AccessTokenResponse.self)
      }
   }
}


