//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

extension Client {

   func getThermostatSummary(headers:  HTTPHeaders) -> EventLoopFuture<AccessTokenResponse> {
      let uri = URI(string: "\(Server.main)/thermostatSummary")
      return send(.GET, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode(AccessTokenResponse.self)
      }
   }
}


