//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

public struct VaporEcobee {

    public static var safeOptionalDecoding = false
    public static var safeArrayDecoding = false
    /// Used to encode Dates when uses as string params
    public static var dateEncodingFormatter = DateFormatter(formatString: "yyyy-MM-dd'T'HH:mm:ssZZZZZ",
                                                            locale: Locale(identifier: "en_US_POSIX"),
                                                            calendar: Calendar(identifier: .gregorian))
}

public enum Server {

    public static let version = "0.1"
    public static let main = "https://api.ecobee.com"
}
