//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

extension Client {
   func refreshToken(headers:  HTTPHeaders) -> EventLoopFuture<[AccessTokenRequest]> {
      send(.POST, headers: headers, to: "/token")
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode([AccessTokenRequest].self)
      }
   }
}


