//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Vapor

extension Client {

   func refreshToken(headers:  HTTPHeaders) -> EventLoopFuture<[AccessTokenRequest]> {
      let uri = URI(string: "\(Server.main)/token")
      return send(.POST, headers: headers, to: uri)
         .flatMapThrowing { clientResponse  in
                return try clientResponse.content.decode([AccessTokenRequest].self)
      }
   }
}


